[package]
name = "myka"
version = "0.1.0"
authors = ["glyph | mycognosist <gnomad@cryptolab.net>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"

[dependencies.hypercore]
git = "https://github.com/datrs/hypercore.git"
